/**
 * AI instructions for Apilot projects.
 *
 * One source, written into each assistant's project-level location so it is
 * picked up automatically — no "connect" step:
 *  - Cursor:      .cursor/skills/apilot/SKILL.md
 *  - Claude Code: .claude/skills/apilot/SKILL.md
 *  - Copilot:     .github/instructions/apilot.instructions.md
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export const SKILL_DESCRIPTION =
  "Work with this project's HTTP APIs through Apilot: run real requests, read real responses, detect breaking changes, and generate typed models. Use whenever writing, fixing, or reviewing code that calls a backend API, or when the user mentions endpoints, API responses, models, or .apilot/.";

export const SKILL_BODY = `# Apilot — real API data for this codebase

This project keeps its API requests, real responses, and version history in \`.apilot/\`.
Apilot's MCP tools let you do everything the Apilot panel can. **Never guess a field name,
type, or nullability — look at a real response.**

## Before writing API code
1. \`list_endpoints\` — find the endpoint id (e.g. \`orders.list\`).
2. \`get_endpoint\` — definition + latest real response. If there is none, \`run_endpoint\`.
3. \`get_schema\` — types, required vs optional, nullable, enums (learned from every saved response).
4. \`generate_code\` (dart | typescript | kotlin | swift) — writes models + a typed call. Use them;
   don't hand-write models for Apilot endpoints.

## When the backend changes
1. \`run_endpoint\` (or \`run_collection\`) — each run is compared to the endpoint's **baseline**.
2. \`diff_endpoint\` — classified changes: **breaking** (field removed, type changed, can now be null,
   likely rename, status changed), **warning** (new enum value), non-breaking (field added, no longer null).
3. \`impact_report\` — exact files/lines that use the changed fields. Fix only those.
4. \`generate_code\` again, then \`set_baseline\` once the new shape is accepted.

## Changing requests
- \`add_endpoint\` / \`update_endpoint\` / \`delete_endpoint\`. Every edit becomes a revision:
  \`list_revisions\`, \`diff_revisions\`, \`restore_revision\`. Pass \`label\` to describe the change.
- \`import_spec\` accepts a cURL command, Postman collection, or OpenAPI document.
- Chain values between requests with \`after: [{ set: { orderId: "$.data[0].id" } }]\`.

## Secrets — hard rules
- Secret values live in the OS keychain (editor) or \`APILOT_SECRET_<name>\` (CI). They are never in files,
  snapshots, or tool results (masked as \`⟦REDACTED⟧\`).
- Reference secrets as \`{{name}}\`. Never write a token, password, or key into any file.
- You may declare a secret (\`set_variable\` with \`type: secret\`), but only the user enters its value.
  If a run reports a missing secret, ask the user to enter it in the Apilot panel → Environments.

## Generated code
- Files with the \`GENERATED BY APILOT\` header are regenerated; don't edit them. Put custom code in
  separate files — Apilot never overwrites files without the header.
- Dart uses freezed + json_serializable: run \`dart run build_runner build\` after generating.

## Without MCP (plain files)
- \`.apilot/collections/<collection>/<name>.yaml\` — endpoint (id = \`<collection>.<name>\`)
- \`.apilot/environments/<env>.yaml\` — variables (\`type: text\` values, \`type: secret\` names only)
- \`.apilot/snapshots/<id>/*.json\` — real responses (redacted); \`baseline\` holds the accepted snapshot id
- \`.apilot/history/<id>/<n>.yaml\` — request revisions
- CLI: \`apilot run <id>\`, \`apilot diff <id>\`, \`apilot codegen <id> --lang dart\`, \`apilot check\`

Endpoint file example:
\`\`\`yaml
name: List orders
method: GET
url: "{{baseUrl}}/orders"
auth: { type: bearer, token: "{{authToken}}" }
query: { page: "1" }
expect: { status: 200 }
after:
  - set: { orderId: "$.data[0].id" }
\`\`\`
`;

export const MARKER = "<!-- managed by Apilot: edits are overwritten; delete this line to keep your own version -->";

export interface AiFile {
  path: string;
  content: string;
}

export function aiFiles(): AiFile[] {
  const skill = `---\nname: apilot\ndescription: ${SKILL_DESCRIPTION}\n---\n${MARKER}\n\n${SKILL_BODY}`;
  return [
    { path: ".cursor/skills/apilot/SKILL.md", content: skill },
    { path: ".claude/skills/apilot/SKILL.md", content: skill },
    { path: ".github/instructions/apilot.instructions.md", content: `---\napplyTo: "**"\n---\n${MARKER}\n\n${SKILL_BODY}` },
  ];
}

/**
 * Write the AI instruction files. Files the user took over (marker line
 * removed) are left alone. Returns the paths that were created or updated.
 */
export function writeAiFiles(root: string): string[] {
  const changed: string[] = [];
  for (const f of aiFiles()) {
    const full = join(root, f.path);
    if (existsSync(full)) {
      const current = readFileSync(full, "utf-8");
      if (current === f.content || !current.includes(MARKER)) continue;
    }
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, f.content);
    changed.push(f.path);
  }
  return changed;
}
