/**
 * Codegen — typed models + a thin API call from an endpoint's real responses.
 *
 * One model walker turns the inferred schema into named classes and enums;
 * each language only renders them:
 *  - Dart/Flutter (flagship): freezed + json_serializable (or plain classes), Dio call
 *  - TypeScript: zod schemas + inferred types, fetch call
 *  - Kotlin: kotlinx.serialization data classes, Retrofit interface
 *  - Swift: Codable structs, URLSession call
 *
 * Like quicktype: identical shapes share one class, array items get singular
 * names, ISO dates become date types, repeated string values become enums
 * (with an `unknown` fallback so a new server value never crashes decoding),
 * and objects keyed by ids become maps.
 *
 * Generated files carry a header. Files without it are hand-written and are
 * never overwritten; identical output is not rewritten (diff-aware regen).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { ApilotSchema, Workspace } from "@apilot/core";

export const LANGUAGES = ["dart", "typescript", "kotlin", "swift"] as const;
export type Language = (typeof LANGUAGES)[number];

export const GENERATED_MARKER = "GENERATED BY APILOT";

export interface EndpointSpec {
  id: string;
  name: string;
  method: string;
  url: string;
  schema: ApilotSchema;
}

export interface GeneratedFile {
  /** path relative to the project root */
  path: string;
  content: string;
  language: Language;
}

export interface RenderOptions {
  /** dart: "freezed" (default) | "plain" */
  flavor?: string;
  /** kotlin package name */
  packageName?: string;
}

// ---------------------------------------------------------------------------
// Workspace integration
// ---------------------------------------------------------------------------

/** Generate files for an endpoint from its learned schema (does not write). */
export function generate(ws: Workspace, endpointId: string, language: string, opts: { outDir?: string; flavor?: string } = {}): GeneratedFile[] {
  const lang = assertLanguage(language);
  const { definition } = ws.endpoint(endpointId);
  const target = ws.project.codegen?.[lang];
  const outDir = opts.outDir ?? target?.output ?? `.apilot/generated/${lang}`;
  const spec = { id: endpointId, name: definition.name, method: definition.method, url: definition.url, schema: ws.schema(endpointId) };
  const content = render(spec, lang, { flavor: opts.flavor ?? target?.flavor, packageName: (target as { package?: string } | undefined)?.package });
  return [{ path: join(outDir, fileName(endpointId, lang)), content, language: lang }];
}

/** Write generated files, skipping hand-written files and unchanged output. */
export function writeGenerated(root: string, files: GeneratedFile[]): { written: string[]; unchanged: string[]; skipped: string[] } {
  const result = { written: [] as string[], unchanged: [] as string[], skipped: [] as string[] };
  for (const f of files) {
    const full = join(root, f.path);
    if (existsSync(full)) {
      const current = readFileSync(full, "utf-8");
      if (current === f.content) {
        result.unchanged.push(f.path);
        continue;
      }
      if (!current.includes(GENERATED_MARKER)) {
        result.skipped.push(f.path);
        continue;
      }
    }
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, f.content);
    result.written.push(f.path);
  }
  return result;
}

export function fileName(endpointId: string, lang: Language): string {
  const base = endpointId.split(/[./-]+/).filter(Boolean);
  switch (lang) {
    case "dart":
      return `${base.map((s) => s.toLowerCase()).join("_")}.dart`;
    case "typescript":
      return `${base.map((s, i) => (i ? pascal(s) : camel(s))).join("")}.ts`;
    case "kotlin":
      return `${pascal(base.join("_"))}.kt`;
    case "swift":
      return `${pascal(base.join("_"))}.swift`;
  }
}

function assertLanguage(language: string): Language {
  if (!(LANGUAGES as readonly string[]).includes(language)) {
    throw new Error(`Unsupported language "${language}". Use one of: ${LANGUAGES.join(", ")}.`);
  }
  return language as Language;
}

// ---------------------------------------------------------------------------
// Model walker
// ---------------------------------------------------------------------------

type T =
  | { k: "string" | "int" | "double" | "bool" | "any" | "date" }
  | { k: "map"; of?: T }
  | { k: "model"; name: string }
  | { k: "enum"; name: string }
  | { k: "list"; of: T };

interface Field {
  key: string;
  /** identifier in the target language (camelCase, sanitized) */
  name: string;
  type: T;
  required: boolean;
  nullable: boolean;
}

interface Model {
  name: string;
  fields: Field[];
}

export interface EnumModel {
  name: string;
  values: string[];
}

/** Keys that are ids rather than field names: `{"17": {...}, "42": {...}}`. */
const DYNAMIC_KEY = /^(\d+|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[0-9a-f]{16,})$/i;
/** Wrapper keys whose items are better named after the endpoint's resource. */
const GENERIC_LIST_KEY = /^(data|items|results|records|list|rows|content|entries|values|payload|docs|nodes|edges)$/i;

const typeSig = (t: T): string =>
  t.k === "model" || t.k === "enum" ? `${t.k}:${t.name}` : t.k === "list" ? `list<${typeSig(t.of)}>` : t.k === "map" ? `map<${t.of ? typeSig(t.of) : ""}>` : t.k;

/**
 * Collect models in dependency order (children before parents).
 * `itemHint` names the items of a top-level or generic array (e.g. "Order" for orders.list).
 */
export function collectModels(schema: ApilotSchema, rootName: string, itemHint?: string): { root: T; models: Model[]; enums: EnumModel[] } {
  const models: Model[] = [];
  const enums: EnumModel[] = [];
  const used = new Set<string>();
  const bySig = new Map<string, string>();

  /** Prefer `candidate`; on a clash with a different shape use `ParentCandidate`, then numbered. */
  const claim = (candidate: string, parent: string): string => {
    let name = !used.has(candidate) ? candidate : !used.has(parent + candidate) ? parent + candidate : "";
    if (!name) for (let i = 2; !name || used.has(name); i++) name = `${parent}${candidate}${i}`;
    used.add(name);
    return name;
  };

  const walk = (s: ApilotSchema | undefined, name: string, parent: string): T => {
    switch (s?.type) {
      case "string": {
        if (s.format) return { k: "date" };
        const values = (s.enum ?? []).filter((v): v is string => typeof v === "string" && v !== "");
        if (values.length < 2) return { k: "string" };
        const sig = `enum:${values.join("\u0000")}`;
        const existing = bySig.get(sig);
        if (existing) return { k: "enum", name: existing };
        const enumName = claim(name, parent);
        bySig.set(sig, enumName);
        enums.push({ name: enumName, values });
        return { k: "enum", name: enumName };
      }
      case "integer":
        return { k: "int" };
      case "number":
        return { k: "double" };
      case "boolean":
        return { k: "bool" };
      case "array":
        return { k: "list", of: walk(s.items, name, parent) };
      case "object": {
        const props = Object.entries(s.properties ?? {});
        if (props.length === 0) return { k: "map" };
        if (props.length >= 2 && props.every(([k]) => DYNAMIC_KEY.test(k))) {
          const shapes = new Set(props.map(([, v]) => JSON.stringify(v)));
          if (shapes.size === 1) return { k: "map", of: walk(props[0]![1], singular(name) === name ? `${name}Value` : singular(name), parent) };
          return { k: "map" };
        }
        const ids = new Set<string>();
        const fields = props.map(([key, prop]): Field => {
          let id = identifier(key);
          for (let i = 2; ids.has(id); i++) id = `${identifier(key)}${i}`;
          ids.add(id);
          return { key, name: id, type: walk(prop, childName(key, prop, itemHint), name), required: s.required.includes(key), nullable: prop.nullable || !prop.type };
        });
        const sig = `model:${JSON.stringify(fields.map((f) => [f.key, typeSig(f.type), f.required, f.nullable]))}`;
        const existing = bySig.get(sig);
        if (existing) return { k: "model", name: existing };
        const modelName = claim(name, parent);
        bySig.set(sig, modelName);
        models.push({ name: modelName, fields });
        return { k: "model", name: modelName };
      }
      default:
        return { k: "any" };
    }
  };

  const top = schema.type === "array" ? itemHint || `${rootName}Item` : rootName;
  return { root: walk(schema, top, rootName), models, enums };
}

/** Class name for a field's value: singular for arrays (`orders` → `Order`). */
function childName(key: string, prop: ApilotSchema, itemHint?: string): string {
  const base = pascal(key) || "Field";
  if (prop.type !== "array") return base;
  if (GENERIC_LIST_KEY.test(key) && itemHint) return itemHint;
  const one = pascal(singular(key));
  return one && one !== base ? one : `${base}Item`;
}

export function singular(word: string): string {
  if (/[^aeiou]ies$/i.test(word)) return word.slice(0, -3) + "y";
  if (/(ss|us|is|news|data)$/i.test(word)) return word;
  if (/(x|ch|sh|ss)es$/i.test(word)) return word.slice(0, -2);
  if (/s$/i.test(word) && word.length > 3) return word.slice(0, -1);
  return word;
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

interface Ctx {
  spec: EndpointSpec;
  rootName: string;
  root: T;
  models: Model[];
  enums: EnumModel[];
  route: Route;
  header: string;
}

export function render(spec: EndpointSpec, language: Language, opts: RenderOptions = {}): string {
  const segments = spec.id.split(/[./-]+/).filter(Boolean);
  const rootName = pascal(segments.join("_")) || "Response";
  const resource = segments.length > 1 ? segments[segments.length - 2]! : segments[0] ?? "";
  const itemHint = pascal(singular(resource)) || undefined;
  const { root, models, enums } = collectModels(spec.schema, rootName, itemHint === rootName ? undefined : itemHint);
  const header = `// ${GENERATED_MARKER} — DO NOT EDIT BY HAND.\n// Source: ${spec.id} (${spec.method} ${spec.url})\n// Regenerate from the Apilot panel or with \`apilot codegen ${spec.id}\`.\n`;
  const ctx: Ctx = { spec, rootName, root, models, enums, route: splitUrl(spec.url), header };

  switch (language) {
    case "dart":
      return opts.flavor === "plain" ? renderDartPlain(ctx) : renderDartFreezed(ctx);
    case "typescript":
      return renderTs(ctx);
    case "kotlin":
      return renderKotlin(ctx, opts.packageName ?? "api");
    case "swift":
      return renderSwift(ctx);
  }
}

interface Route {
  /** path segments; `param` entries are path variables */
  parts: { text?: string; param?: string }[];
  params: string[];
  absolute: boolean;
}

/** `{{baseUrl}}/orders/{{id}}` → path `/orders/{id}` with params [id]; a leading variable is the base URL. */
function splitUrl(url: string): Route {
  let rest = url.replace(/^\s*\{\{\s*\w+\s*\}\}/, "");
  const absolute = /^https?:\/\//.test(rest);
  rest = rest.split("?")[0] ?? "";
  const parts: Route["parts"] = [];
  const params: string[] = [];
  let last = 0;
  for (const m of rest.matchAll(/\{\{\s*(\w+)\s*\}\}|\{(\w+)\}/g)) {
    if (m.index! > last) parts.push({ text: rest.slice(last, m.index) });
    const p = identifier(m[1] ?? m[2]!);
    parts.push({ param: p });
    if (!params.includes(p)) params.push(p);
    last = m.index! + m[0].length;
  }
  if (last < rest.length) parts.push({ text: rest.slice(last) });
  return { parts, params, absolute };
}

const hasBody = (method: string) => !["GET", "HEAD", "DELETE", "OPTIONS"].includes(method.toUpperCase());
const displayPath = (route: Route) => route.parts.map((p) => (p.param ? `{${p.param}}` : p.text)).join("");

/** Enum case identifiers, unique, plus a fallback case name that doesn't clash. */
function enumCases(values: string[], style: "camel" | "upper", reserved: Set<string> = new Set()): { cases: { name: string; value: string }[]; unknown: string } {
  const seen = new Set<string>();
  const cases = values.map((value) => {
    let name = style === "upper" ? words(value).join("_").toUpperCase() || "EMPTY" : identifier(value) === "field" && !value ? "empty" : identifier(value);
    if (/^\d/.test(name)) name = style === "upper" ? `V_${name}` : `n${name}`;
    if (reserved.has(name)) name = `${name}Value`;
    const base = name;
    for (let i = 2; seen.has(name); i++) name = `${base}${i}`;
    seen.add(name);
    return { name, value };
  });
  const unknown = [style === "upper" ? "UNKNOWN" : "unknown", style === "upper" ? "UNRECOGNIZED" : "unrecognized"].find((n) => !seen.has(n))!;
  return { cases, unknown };
}

const escapeDq = (s: string) => s.replace(/["\\$]/g, "\\$&");

// --- Dart ------------------------------------------------------------------

/** Members every Dart enum already has. */
const DART_ENUM_RESERVED = new Set(["values", "index", "name", "hashCode", "runtimeType", "jsonValue"]);

function dartType(t: T): string {
  switch (t.k) {
    case "string": return "String";
    case "int": return "int";
    case "double": return "double";
    case "bool": return "bool";
    case "date": return "DateTime";
    case "map": return `Map<String, ${t.of ? dartType(t.of) : "dynamic"}>`;
    case "any": return "Object";
    case "model":
    case "enum": return t.name;
    case "list": return `List<${dartType(t.of)}${t.of.k === "any" ? "?" : ""}>`;
  }
}

function dartFrom(t: T, v: string): string {
  switch (t.k) {
    case "string": return `${v} as String`;
    case "int": return `(${v} as num).toInt()`;
    case "double": return `(${v} as num).toDouble()`;
    case "bool": return `${v} as bool`;
    case "date": return `DateTime.parse(${v} as String)`;
    case "map": return t.of ? `(${v} as Map<String, dynamic>).map((k, e) => MapEntry(k, ${dartFrom(t.of, "e")}))` : `${v} as Map<String, dynamic>`;
    case "any": return v;
    case "model": return `${t.name}.fromJson(${v} as Map<String, dynamic>)`;
    case "enum": return `${t.name}.fromJson(${v} as String)`;
    case "list": return `(${v} as List<dynamic>).map((e) => ${dartFrom(t.of, "e")}).toList()`;
  }
}

const needsConversion = (t: T): boolean =>
  t.k === "model" || t.k === "enum" || t.k === "date" || ((t.k === "list" || t.k === "map") && !!t.of && needsConversion(t.of));

function dartTo(t: T, v: string, optional: boolean): string {
  const q = optional ? "?" : "";
  if (t.k === "model" || t.k === "enum") return `${v}${q}.toJson()`;
  if (t.k === "date") return `${v}${q}.toIso8601String()`;
  if (t.k === "list" && needsConversion(t.of)) return `${v}${q}.map((e) => ${dartTo(t.of, "e", false)}).toList()`;
  if (t.k === "map" && t.of && needsConversion(t.of)) return `${v}${q}.map((k, e) => MapEntry(k, ${dartTo(t.of, "e", false)}))`;
  return v;
}

function dartString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\$/g, "\\$");
}

function dartPath(route: Route): string {
  return `'${route.parts.map((p) => (p.param ? `\${${p.param}}` : dartString(p.text!))).join("")}'`;
}

function dartApi({ spec, rootName, root, route }: Ctx): string {
  const args = [
    ...route.params.map((p) => `required String ${p}`),
    "Map<String, dynamic>? queryParameters",
    ...(hasBody(spec.method) ? ["Object? data"] : []),
    "Options? options",
    "CancelToken? cancelToken",
  ];
  const result = root.k === "any" ? "response.data" : dartFrom(root, "response.data");
  const returnType = root.k === "any" ? "Object?" : dartType(root);
  return `class ${rootName}Api {
  ${rootName}Api(this._dio);

  final Dio _dio;

  /// ${spec.name} — ${spec.method} ${displayPath(route)}
  Future<${returnType}> call({
${args.map((a) => `    ${a},`).join("\n")}
  }) async {
    final response = await _dio.request<Object?>(
      ${dartPath(route)},
      queryParameters: queryParameters,${hasBody(spec.method) ? "\n      data: data," : ""}
      options: (options ?? Options()).copyWith(method: '${spec.method.toUpperCase()}'),
      cancelToken: cancelToken,
    );
    return ${result};
  }
}
`;
}

/** The enum a field holds directly or as list items (for json_serializable's unknownEnumValue). */
const fieldEnum = (t: T): string | undefined => (t.k === "enum" ? t.name : t.k === "list" && t.of.k === "enum" ? t.of.name : undefined);

/** Enhanced enum with a lookup that falls back to `unknown`; json_serializable reads `jsonValue` too. */
function dartEnum(e: EnumModel, annotated: boolean): { code: string; unknown: string } {
  const { cases, unknown } = enumCases(e.values, "camel", DART_ENUM_RESERVED);
  const code = `${annotated ? "@JsonEnum(valueField: 'jsonValue')\n" : ""}enum ${e.name} {
${cases.map((c) => `  ${c.name}('${dartString(c.value)}'),`).join("\n")}
  /// A value this app version doesn't know yet.
  ${unknown}('');

  const ${e.name}(this.jsonValue);

  final String jsonValue;

  static ${e.name} fromJson(String value) => values.firstWhere((e) => e.jsonValue == value, orElse: () => ${unknown});

  String toJson() => jsonValue;
}
`;
  return { code, unknown };
}

function renderDartFreezed(ctx: Ctx): string {
  const { spec, models, enums, header } = ctx;
  const base = fileName(spec.id, "dart").replace(/\.dart$/, "");
  const unknownOf = new Map<string, string>();
  const enumBlocks = enums.map((e) => {
    const { code, unknown } = dartEnum(e, true);
    unknownOf.set(e.name, unknown);
    return code;
  });
  const classes = models.map((m) => {
    const params = m.fields.map((f) => {
      const optional = !f.required || f.nullable;
      const opts = [
        ...(f.key !== f.name ? [`name: '${dartString(f.key)}'`] : []),
        ...(fieldEnum(f.type) ? [`unknownEnumValue: ${fieldEnum(f.type)}.${unknownOf.get(fieldEnum(f.type)!)}`] : []),
      ];
      const key = opts.length ? `@JsonKey(${opts.join(", ")}) ` : "";
      return `    ${key}${optional ? "" : "required "}${dartType(f.type)}${optional ? "?" : ""} ${f.name},`;
    });
    return `@freezed
abstract class ${m.name} with _$${m.name} {
  const factory ${m.name}({
${params.join("\n")}
  }) = _${m.name};

  factory ${m.name}.fromJson(Map<String, dynamic> json) => _$${m.name}FromJson(json);
}
`;
  });
  const blocks = [...enumBlocks, ...classes];
  const annotated = blocks.length > 0;
  return `${header}// ignore_for_file: invalid_annotation_target

import 'package:dio/dio.dart';
${annotated ? "import 'package:freezed_annotation/freezed_annotation.dart';\n" : ""}
${models.length ? `part '${base}.freezed.dart';\npart '${base}.g.dart';\n\n` : ""}${blocks.join("\n")}${blocks.length ? "\n" : ""}${dartApi(ctx)}`;
}

function renderDartPlain(ctx: Ctx): string {
  const { models, enums, header } = ctx;
  const enumBlocks = enums.map((e) => dartEnum(e, false).code);
  const classes = models.map((m) => {
    const opt = (f: Field) => !f.required || f.nullable;
    return `class ${m.name} {
  const ${m.name}({
${m.fields.map((f) => `    ${opt(f) ? "" : "required "}this.${f.name},`).join("\n")}
  });

  factory ${m.name}.fromJson(Map<String, dynamic> json) => ${m.name}(
${m.fields.map((f) => {
  const v = `json['${dartString(f.key)}']`;
  return `        ${f.name}: ${opt(f) ? `${v} == null ? null : ${dartFrom(f.type, v)}` : dartFrom(f.type, v)},`;
}).join("\n")}
      );

${m.fields.map((f) => `  final ${dartType(f.type)}${opt(f) ? "?" : ""} ${f.name};`).join("\n")}

  ${m.name} copyWith({
${m.fields.map((f) => `    ${dartType(f.type)}? ${f.name},`).join("\n")}
  }) =>
      ${m.name}(
${m.fields.map((f) => `        ${f.name}: ${f.name} ?? this.${f.name},`).join("\n")}
      );

  Map<String, dynamic> toJson() => {
${m.fields.map((f) => `        '${dartString(f.key)}': ${dartTo(f.type, f.name, opt(f))},`).join("\n")}
      };
}
`;
  });
  const blocks = [...enumBlocks, ...classes];
  return `${header}
import 'package:dio/dio.dart';

${blocks.join("\n")}${blocks.length ? "\n" : ""}${dartApi(ctx)}`;
}

// --- TypeScript --------------------------------------------------------------

function zod(t: T): string {
  switch (t.k) {
    case "string": return "z.string()";
    case "int": return "z.number().int()";
    case "double": return "z.number()";
    case "bool": return "z.boolean()";
    case "date": return "z.coerce.date()";
    case "map": return `z.record(z.string(), ${t.of ? zod(t.of) : "z.unknown()"})`;
    case "any": return "z.unknown()";
    case "model":
    case "enum": return `${t.name}Schema`;
    case "list": return `z.array(${zod(t.of)})`;
  }
}

function renderTs(ctx: Ctx): string {
  const { spec, rootName, root, models, enums, route, header } = ctx;
  const key = (k: string) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k));
  const blocks = [
    ...enums.map((e) => {
      const values = [...new Set([...e.values, "unknown"])].map((v) => JSON.stringify(v)).join(", ");
      return `/** "unknown" = a value this app version doesn't know yet. */\nexport const ${e.name}Schema = z.enum([${values}]).catch("unknown");\nexport type ${e.name} = z.infer<typeof ${e.name}Schema>;\n`;
    }),
    ...models.map((m) => {
      const fields = m.fields.map((f) => {
        const mod = !f.required && f.nullable ? ".nullish()" : f.nullable ? ".nullable()" : !f.required ? ".optional()" : "";
        return `  ${key(f.key)}: ${zod(f.type)}${mod},`;
      });
      return `export const ${m.name}Schema = z.object({\n${fields.join("\n")}\n});\nexport type ${m.name} = z.infer<typeof ${m.name}Schema>;\n`;
    }),
  ];
  const rootIsModel = root.k === "model" && root.name === rootName;
  if (!rootIsModel) blocks.push(`export const ${rootName}Schema = ${zod(root)};\nexport type ${rootName} = z.infer<typeof ${rootName}Schema>;\n`);

  const fn = camel(rootName);
  const path = route.parts.map((p) => (p.param ? `\${encodeURIComponent(String(req.params.${p.param}))}` : p.text!.replace(/[`$\\]/g, "\\$&"))).join("");
  const paramsType = route.params.length ? `params: { ${route.params.map((p) => `${p}: string | number`).join("; ")} };\n  ` : "";
  const bodyOpt = hasBody(spec.method) ? "body?: unknown;\n  " : "";
  return `${header}
import { z } from "zod";

${blocks.join("\n")}
export interface ${rootName}Request {
  ${route.absolute ? "" : "baseUrl: string;\n  "}${paramsType}query?: Record<string, string | number | boolean>;
  ${bodyOpt}init?: RequestInit;
}

/** ${spec.name} — ${spec.method} ${displayPath(route)} */
export async function ${fn}(req: ${rootName}Request): Promise<${rootName}> {
  const url = new URL(${route.absolute ? `\`${path}\`` : `\`\${req.baseUrl.replace(/\\/$/, "")}${path}\``});
  for (const [k, v] of Object.entries(req.query ?? {})) url.searchParams.set(k, String(v));
  const res = await fetch(url, {
    method: "${spec.method.toUpperCase()}",
    ...req.init,
    headers: { Accept: "application/json",${hasBody(spec.method) ? ' ...(req.body !== undefined ? { "Content-Type": "application/json" } : {}),' : ""} ...(req.init?.headers as Record<string, string> | undefined) },${hasBody(spec.method) ? "\n    body: req.body !== undefined ? JSON.stringify(req.body) : undefined," : ""}
  });
  if (!res.ok) throw new Error(\`${spec.method.toUpperCase()} \${url.pathname} failed with \${res.status}\`);
  return ${rootName}Schema.parse(await res.json());
}
`.replace(/\n{3,}/g, "\n\n");
}

// --- Kotlin ------------------------------------------------------------------

function kotlinType(t: T): string {
  switch (t.k) {
    case "string":
    case "date": return "String";
    case "int": return "Long";
    case "double": return "Double";
    case "bool": return "Boolean";
    case "map": return t.of ? `Map<String, ${kotlinType(t.of)}>` : "JsonObject";
    case "any": return "JsonElement";
    case "model":
    case "enum": return t.name;
    case "list": return `List<${kotlinType(t.of)}>`;
  }
}

function renderKotlin(ctx: Ctx, pkg: string): string {
  const { spec, rootName, root, models, enums, route, header } = ctx;
  const enumBlocks = enums.map((e) => {
    const { cases, unknown } = enumCases(e.values, "upper");
    return `@Serializable(with = ${e.name}Serializer::class)
enum class ${e.name}(val value: String) {
${cases.map((c) => `    ${c.name}("${escapeDq(c.value)}"),`).join("\n")}
    /** A value this app version doesn't know yet. */
    ${unknown}(""),
}

object ${e.name}Serializer : KSerializer<${e.name}> {
    override val descriptor = PrimitiveSerialDescriptor("${e.name}", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): ${e.name} {
        val raw = decoder.decodeString()
        return ${e.name}.values().firstOrNull { it.value == raw } ?: ${e.name}.${unknown}
    }
    override fun serialize(encoder: Encoder, value: ${e.name}) = encoder.encodeString(value.value)
}
`;
  });
  const classes = models.map((m) => `@Serializable
data class ${m.name}(
${m.fields.map((f) => {
  const optional = !f.required || f.nullable;
  const doc = f.type.k === "date" ? " // ISO-8601" : "";
  return `    @SerialName("${escapeDq(f.key)}") val ${f.name}: ${kotlinType(f.type)}${optional ? "? = null" : ""},${doc}`;
}).join("\n")}
)
`);
  const method = spec.method.toUpperCase();
  const path = route.parts.map((p) => (p.param ? `{${p.param}}` : p.text!)).join("").replace(/^\//, "");
  const args = [
    ...route.params.map((p) => `@Path("${p}") ${p}: String`),
    "@QueryMap query: Map<String, String> = emptyMap()",
    ...(hasBody(method) ? ["@Body body: JsonElement"] : []),
  ];
  const annotation = method === "OPTIONS" ? `@HTTP(method = "OPTIONS", path = "${path}")` : `@${method}("${path}")`;
  const enumImports = enums.length
    ? "import kotlinx.serialization.KSerializer\nimport kotlinx.serialization.descriptors.PrimitiveKind\nimport kotlinx.serialization.descriptors.PrimitiveSerialDescriptor\nimport kotlinx.serialization.encoding.Decoder\nimport kotlinx.serialization.encoding.Encoder\n"
    : "";
  const blocks = [...enumBlocks, ...classes];
  return `${header}
package ${pkg}

${enumImports}import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import retrofit2.http.*

${blocks.join("\n")}${blocks.length ? "\n" : ""}interface ${rootName}Api {
    /** ${spec.name} */
    ${annotation}
    suspend fun call(
${args.map((a) => `        ${a},`).join("\n")}
    ): ${method === "HEAD" ? "retrofit2.Response<Unit>" : kotlinType(root)}
}
`;
}

// --- Swift -------------------------------------------------------------------

function swiftType(t: T): string {
  switch (t.k) {
    case "string":
    case "date": return "String";
    case "int": return "Int";
    case "double": return "Double";
    case "bool": return "Bool";
    case "map": return `[String: ${t.of ? swiftType(t.of) : "JSONValue"}]`;
    case "any": return "JSONValue";
    case "model":
    case "enum": return t.name;
    case "list": return `[${swiftType(t.of)}]`;
  }
}

const SWIFT_JSON_VALUE = `/// Any JSON value, for fields whose shape Apilot could not infer.
enum JSONValue: Codable, Equatable {
    case string(String), number(Double), bool(Bool), object([String: JSONValue]), array([JSONValue]), null

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null }
        else if let v = try? c.decode(Bool.self) { self = .bool(v) }
        else if let v = try? c.decode(Double.self) { self = .number(v) }
        else if let v = try? c.decode(String.self) { self = .string(v) }
        else if let v = try? c.decode([JSONValue].self) { self = .array(v) }
        else { self = .object(try c.decode([String: JSONValue].self)) }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .string(let v): try c.encode(v)
        case .number(let v): try c.encode(v)
        case .bool(let v): try c.encode(v)
        case .object(let v): try c.encode(v)
        case .array(let v): try c.encode(v)
        case .null: try c.encodeNil()
        }
    }
}
`;

function renderSwift(ctx: Ctx): string {
  const { spec, rootName, root, models, enums, route, header } = ctx;
  const enumBlocks = enums.map((e) => {
    const { cases, unknown } = enumCases(e.values, "camel");
    return `enum ${e.name}: String, Codable, Equatable {
${cases.map((c) => `    case ${c.name}${c.name !== c.value ? ` = "${c.value.replace(/["\\]/g, "\\$&")}"` : ""}`).join("\n")}
    /// A value this app version doesn't know yet.
    case ${unknown} = ""

    init(from decoder: Decoder) throws {
        self = ${e.name}(rawValue: try decoder.singleValueContainer().decode(String.self)) ?? .${unknown}
    }
}
`;
  });
  const structs = models.map((m) => {
    const keys = m.fields.map((f) => `        case ${f.name}${f.key !== f.name ? ` = "${f.key.replace(/["\\]/g, "\\$&")}"` : ""}`);
    return `struct ${m.name}: Codable, Equatable {
${m.fields.map((f) => `    let ${f.name}: ${swiftType(f.type)}${!f.required || f.nullable ? "?" : ""}${f.type.k === "date" ? " // ISO-8601" : ""}`).join("\n")}

    enum CodingKeys: String, CodingKey {
${keys.join("\n")}
    }
}
`;
  });
  const blocks = [...enumBlocks, ...structs];
  const usesAny = /JSONValue/.test(blocks.join("") + swiftType(root));
  const path = route.parts.map((p) => (p.param ? `\\(${p.param})` : p.text!.replace(/["\\]/g, "\\$&"))).join("");
  const method = spec.method.toUpperCase();
  const args = [
    ...(route.absolute ? [] : ["baseURL: URL"]),
    ...route.params.map((p) => `${p}: String`),
    "query: [String: String] = [:]",
    ...(hasBody(method) ? ["body: Data? = nil"] : []),
    "session: URLSession = .shared",
  ];
  const urlExpr = route.absolute
    ? `URLComponents(string: "${path}")!`
    : `URLComponents(url: baseURL.appendingPathComponent("${path.replace(/^\//, "")}"), resolvingAgainstBaseURL: false)!`;
  return `${header}
import Foundation

${usesAny ? SWIFT_JSON_VALUE + "\n" : ""}${blocks.join("\n")}${blocks.length ? "\n" : ""}enum ${rootName}API {
    /// ${spec.name}
    static func call(
${args.map((a) => `        ${a}`).join(",\n")}
    ) async throws -> ${swiftType(root)} {
        var components = ${urlExpr}
        if !query.isEmpty { components.queryItems = query.map { URLQueryItem(name: $0.key, value: $0.value) } }
        var request = URLRequest(url: components.url!)
        request.httpMethod = "${method}"
        request.setValue("application/json", forHTTPHeaderField: "Accept")${hasBody(method) ? `
        if let body {
            request.httpBody = body
            request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        }` : ""}
        let (data, response) = try await session.data(for: request)
        if let http = response as? HTTPURLResponse, !(200..<300).contains(http.statusCode) {
            throw URLError(.badServerResponse)
        }
        return try JSONDecoder().decode(${swiftType(root)}.self, from: data)
    }
}
`;
}

// ---------------------------------------------------------------------------
// Names
// ---------------------------------------------------------------------------

const RESERVED = new Set([
  // shared across Dart / TS / Kotlin / Swift
  "class", "default", "new", "switch", "case", "return", "if", "else", "for", "while", "do", "break", "continue",
  "var", "val", "let", "const", "final", "static", "this", "super", "null", "true", "false", "is", "in", "as",
  "enum", "extends", "import", "export", "package", "interface", "object", "fun", "func", "struct", "protocol",
  "operator", "try", "catch", "throw", "throws", "typealias", "where", "when", "void", "dynamic", "required",
  "extension", "self", "Type", "init", "deinit", "internal", "private", "public", "open", "override", "get", "set",
  // members generated models already have
  "hashCode", "runtimeType", "toString", "copyWith", "toJson", "noSuchMethod",
]);

function words(s: string): string[] {
  return s
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean);
}

export function camel(s: string): string {
  return words(s).map((w, i) => (i ? w[0]!.toUpperCase() + w.slice(1).toLowerCase() : w.toLowerCase())).join("");
}

export function pascal(s: string): string {
  const c = camel(s);
  return c ? c[0]!.toUpperCase() + c.slice(1) : "";
}

function identifier(key: string): string {
  let id = camel(key) || "field";
  if (/^\d/.test(id)) id = `n${id}`;
  return RESERVED.has(id) ? `${id}Value` : id;
}
